### ISSUE TITLE
[feature] 제출(Submission) 도메인 기본기능 구현

### ISSUE THREAD

**Issue by silxbro** [silxbro/algo-arena#4]
## Feature Issue
제출 도메인 관련 Entity를 정의하고, 관련 기본기능(CRUD)을 구현합니다.

## TODO
- [x] 제출(Submission) Entity/DTO 설계 및 생성
- [x] 제출(Submission) 생성 API
- [x] 제출(Submission) 조회 API

### 제출 조회
- 문제(번호), 닉네임, 언어, 결과를 조합한 조건으로 제출 검색 가능
  - QueryDSL 사용 예정
