### ISSUE TITLE
[feature] 테스트방(Room) 도메인 기본기능 구현

### ISSUE THREAD

**Issue by silxbro** [silxbro/algo-arena#7]
## Feature Issue
테스트방 도메인 관련 Entity를 정의하고, 관련 기본기능(CRUD)을 구현합니다.

## TODO
- [x] 테스트방(Room) Entity/DTO 설계 및 생성
- [x] 테스트방(Room) 생성 API
- [x] 테스트방(Room) 조회 API
- [x] 테스트방(Room) 수정 API
- [x] 테스트방(Room) 삭제 API

### Redis(In-Memory DB) 적용
- 테스트방 도메인의 경우, 시스템이 종료되거나 참가자가 없을 경우 사라질 수 있는 특성을 기반으로 일시적이고 휘발적인 데이터 특성을 가지고 있습니다. 따라서, 영구성 DB보다는 인메모리 DB인 Redis가 저장소로 적합하다고 판단하였습니다.

### 조회(검색) 기능
- 이름(대소문자 구분 없음), 최대 참가자수, 구현 언어, 문제 수(범위), 제한시간(범위) 조건을 복합적으로 검색 가능하도록 구현할 계획입니다.
