### ISSUE TITLE
[feature] 채팅(Chat) 도메인 기본기능 구현

### ISSUE THREAD

**Issue by silxbro** [silxbro/algo-arena#9]
## Feature Issue
- 채팅 도메인 관련 Entity 및 dto를 설계합니다.
- 채팅 도메인 관련 기본기능(CRUD)을 구현합니다.
  - 채팅 생성/ 조회/ 수정/ 삭제/ 전송/ 저장
- 실시간 메시지 전송 기능을 구현합니다.
  - WebSocket 설정 및 Handler 구현

## TODO
- [x] 채팅(Chat) Entity/DTO 설계 및 생성
- [x] 채팅(Chat) 생성 API 구현
- [x] 채팅(Chat) 저장 API 구현
- [x] 채팅(Chat) 조회 API 구현
- [x] 채팅(Chat) 수정 API 구현
- [x] 채팅(Chat) 삭제 API 구현
- [ ] 채팅(Chat) 전송 API 구현
- [ ] 실시간 채팅 구현

### 테스트방별 채팅 메시지 저장: Redis(In-Memory DB) 적용
- 채팅 도메인은 테스트방에 종속되어 있으면서, 일시적이고 휘발성이 강한 데이터 특성을 가지고 있습니다. 따라서, 영구성 DB보다는 인메모리 DB인 Redis가 저장소로 적합하다고 판단하였습니다.
- 중간에 테스트방에 입장하는 참가자들도 입장 이전의 메시지들을 모두 확인할 수 있습니다.
### 채팅 타입
- 참가자가 직접 전송하는 채팅 외에 알림성 메시지도 채팅 기능을 이용하여 전송되기 때문에, 채팅 타입을 적용할 예정입니다.
